[build-system]
requires = [
    "setuptools>=45",
    "wheel",
    "setuptools_scm>=6.2",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "device_test_core/_version.py"

#[tool.setuptools.dynamic]
#readme = {file = ["README.md"]}

[project]
name = "device_test_core"
description = "Device test library"
requires-python = ">=3.7"
keywords = ["device", "testing"]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dynamic = ["version", "dependencies", "readme"]
dependencies = [
  'python-dotenv >= 0.20.0, < 0.21.0',
  'randomname >= 0.1.5, < 0.2.0',
  'tenacity >= 8.1.0, < 9.0.0',
  # 'docker[ssh] >= 4.2.2, < 5',

  # Conditional
  #'backports.shutil_get_terminal_size == 1.0.0; python_version < "3.3"',
  #'colorama >= 0.4, < 1; sys_platform == "win32"',
]

[project.optional-dependencies]
ssh = [
    'paramiko >= 2.12.0, < 2.13.0',
    'scp >= 0.14.4, < 0.15.0',
]
local = []
docker = [
    'docker >= 6.0.1, < 6.1.0'
]
